# Taken from https://github.com/torivarm/iac-terraform/blob/main/.github/workflows/validate.yml and modified to fit my needs

name: Validate Infrastructure

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'Mandatory Assignments/Assignment02/kristoju-oppg2/**'

jobs:
  terraform:
    name: 'Validate'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./Mandatory Assignments/Assignment02/kristoju-oppg2
      
    steps:
      - uses: actions/checkout@v4
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}          
      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}
      - name: Set Validation Completed
        id: validation_completed
        run: echo "Validation Completed" # This step signals the completion of the workflow
        continue-on-error: true
